### ISSUE TITLE
how to run the new action with docker and google auth

### ISSUE THREAD

**Issue by ba-encodify** [dextercai/lego-action#5]
we used your version 1 together with google auth

https://github.com/google-github-actions/auth

and then step after auth was 

google-github-actions/setup-gcloud@v2

then the lego run 

```
      - uses: dextercai/lego-action@main
        with:
          version: latest
          accounts-tar-base64: ${{ env.LEGO_ACCOUNT }}
          lego-envs: GCE_PROJECT=${{ env.GCP_DNS_PROJECT }}
          lego-server: ${{ env.LEGO_SERVER }}
          email: ${{ env.ACME_EMAIL }}
          lego-dns-provider: gcloud
          domains: ${{ env.HOSTNAME }}
```

but now it pulls the version 2 with docker.
The easy fix is just request @v1

but would love it to work with the new version.
but not sure howto configure it

```
      - uses: dextercai/lego-action@main
        with:
          version: latest
          accounts-tar-base64: ${{ env.LEGO_ACCOUNT }}
          lego-envs: GCE_PROJECT=${{ env.GCP_DNS_PROJECT }}
          lego-server: ${{ env.LEGO_SERVER }}
          email: ${{ env.ACME_EMAIL }}
          lego-dns-provider: gcloud
          domains: ${{ env.HOSTNAME }}
```
so we dont have gce_service_account_file
any way to mount the gcloud dir also? or so

**Comment by dextercai** [comment]
I think I could assign a path for mount.

**Comment by dextercai** [comment]
Pls use tag `v2.1-release` or `main`, and **make sure GCE_SERVICE_ACCOUNT_FILE is exist in the github.workspace path**. 

```
      - uses: dextercai/lego-action@main
        with:
          version: latest
          accounts-tar-base64: ${{ env.LEGO_ACCOUNT }}
          lego-envs: GCE_PROJECT=${{ env.GCP_DNS_PROJECT }},GCE_SERVICE_ACCOUNT_FILE=${{ your_file_path_here }}
          lego-server: ${{ env.LEGO_SERVER }}
          email: ${{ env.ACME_EMAIL }}
          lego-dns-provider: gcloud
          domains: ${{ env.HOSTNAME }}

```
